---
application:
  name: "chashi-admin"
  project: "chashi-admin"
  organization: "QoveryCommunity"
databases:
- type: "MYSQL"
  name: "chashi-db"
  version: "8.0"
routers:
- name: "main-chashi-admin"
  routes:
  - application_name: "chashi-admin"
    paths:
    - "/*"
